// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiekSMAx5De-yDIfKpVXkToJDa1ZRYXI',
    appId: '1:195589649245:web:141e696061a96e3ff56eb4',
    messagingSenderId: '195589649245',
    projectId: 'untangled-19bd8',
    authDomain: 'untangled-19bd8.firebaseapp.com',
    storageBucket: 'untangled-19bd8.appspot.com',
    measurementId: 'G-87E11YLD8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDq3LEpv2dOIBBjZur3TpgApJj6tD2NHE',
    appId: '1:195589649245:android:ef71261adaeb3f13f56eb4',
    messagingSenderId: '195589649245',
    projectId: 'untangled-19bd8',
    storageBucket: 'untangled-19bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkr7xBf-M00X_mczrjb1cHj1S8m9l2-hM',
    appId: '1:195589649245:ios:de4a294587118c3df56eb4',
    messagingSenderId: '195589649245',
    projectId: 'untangled-19bd8',
    storageBucket: 'untangled-19bd8.appspot.com',
    iosBundleId: 'com.example.healthbot',
  );
}
